export const wordBank = [
  {
    id: "wb-misty",
    word: "霧靄",
    meaning: "霧氣籠罩的朦朧景象，常用於清晨、山林或帶有距離感的場景。",
    tags: ["景物", "氛圍", "朦朧"],
    example: "遠山浸在霧靄裡，像一封尚未拆開的信。",
    tone: "古風",
  },
  {
    id: "wb-gentle",
    word: "溫存",
    meaning: "溫柔而留戀的情意，也可指短暫的親密與安慰。",
    tags: ["情感", "親密", "柔和"],
    example: "那句話沒有承諾，卻仍留下片刻溫存。",
    tone: "溫柔",
  },
  {
    id: "wb-silent",
    word: "緘默",
    meaning: "保持沉默，不說出口，語感比沉默更正式、更克制。",
    tags: ["狀態", "沉默", "克制"],
    example: "他在眾人的追問裡緘默，只把目光移向窗外。",
    tone: "正式",
  },
  {
    id: "wb-melancholy",
    word: "悵然若失",
    meaning: "心裡失落惆悵，好像失去了什麼重要之物。",
    tags: ["成語", "失落", "惆悵"],
    example: "散場後她站在空椅之間，忽然悵然若失。",
    tone: "悲傷",
  },
  {
    id: "wb-academic",
    word: "脈絡",
    meaning: "事物發展的條理、背景與相互關聯，適合論述分析。",
    tags: ["論文", "分析", "結構"],
    example: "本文將先梳理研究脈絡，再討論工具如何影響寫作行為。",
    tone: "學術",
  },
  {
    id: "wb-inference",
    word: "推論",
    meaning: "根據已知資料或前提推出結論。",
    tags: ["論文", "邏輯", "研究"],
    example: "由訪談結果可推論，學生更重視工具的整理能力而非生成能力。",
    tone: "學術",
  },
  {
    id: "wb-tender",
    word: "低迴",
    meaning: "聲音、情緒或思緒反覆縈繞，帶有婉轉不散的感覺。",
    tags: ["聲音", "情緒", "縈繞"],
    example: "雨聲在屋簷下低迴，替沉默補上了尾音。",
    tone: "溫柔",
  },
  {
    id: "wb-old-style",
    word: "故人",
    meaning: "舊識、老朋友，也常帶有久別重逢或往事感。",
    tags: ["人物", "重逢", "往事"],
    example: "燈火闌珊處，他像一位不該再出現的故人。",
    tone: "古風",
  },
  {
    id: "wb-formal",
    word: "界定",
    meaning: "明確說明概念、範圍或標準。",
    tags: ["論文", "概念", "正式"],
    example: "在進入分析前，本文先界定長篇寫作工具的使用範圍。",
    tone: "正式",
  },
  {
    id: "wb-sorrow",
    word: "無可挽回",
    meaning: "事情已經發生或失去，不能再補救。",
    tags: ["命運", "失去", "轉折"],
    example: "她聽見門鎖落下的聲音，才明白一切已無可挽回。",
    tone: "悲傷",
  },
];
